name: Question
description: Ask a question
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a question !

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search in the repository [issues](https://github.com/vtemplier/vscode-netron/issues) to see if a similar question already exists.
      options:
        - label: >
            I have searched among the issues and discussions and found no similar questions.
          required: true

  - type: textarea
    attributes:
      label: Question
      description: What is your question ?
      placeholder: |
        Please include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Anything else you would like to share ?